/**
 * A map of locale identifiers to translated labels.
 *
 * Locale identifiers should use BCP-47 language tags such as
 * `en`, `ar`, `fr`, or `zh-CN`.
 *
 * @example
 * {
 *   en: "Core",
 *   ar: "النواة",
 *   fr: "Noyau"
 * }
 */
export interface SidebarTranslations {
  [locale: string]: string;
}

/**
 * A nested documentation structure.
 *
 * Object keys represent directory names.
 * An empty object represents a leaf documentation directory.
 *
 * @example
 * {
 *   core: {
 *     ui: {
 *       utilities: {},
 *       "ui-constructors": {}
 *     },
 *     math: {}
 *   },
 *   wrapper: {}
 * }
 */
export interface SidebarStructure {
  [name: string]: SidebarStructure;
}

/**
 * Options used when generating sidebar items.
 */
export interface CreateSidebarOptions {
  /**
   * Locale used for the generated `label`.
   *
   * @default "en"
   */
  locale?: string;

  /**
   * Root directory used to build documentation paths.
   *
   * @default "reference"
   *
   * @example
   * "reference"
   *
   * @example
   * "api/reference"
   */
  rootDirectory?: string;
}

/**
 * A Starlight-compatible autogenerated sidebar item.
 *
 * @example
 * {
 *   autogenerate: {
 *     directory: "reference/core/math"
 *   }
 * }
 */
export interface SidebarAutogenerateItem {
  autogenerate: {
    directory: string;
  };
}

/**
 * A generated Starlight sidebar group.
 *
 * Groups contain a label and nested sidebar items.
 *
 * @example
 * {
 *   label: "Core",
 *   translations: {
 *     ar: "النواة"
 *   },
 *   items: [
 *     {
 *       autogenerate: {
 *         directory: "reference/core/math"
 *       }
 *     }
 *   ]
 * }
 */
export interface SidebarGroup {
  /**
   * Label for the default locale.
   */
  label: string;

  /**
   * Labels for other supported locales.
   */
  translations?: SidebarTranslations;

  /**
   * Nested sidebar groups or autogenerated directory entries.
   */
  items: Array<SidebarGroup | SidebarAutogenerateItem>;
}

/**
 * A flattened translation map.
 *
 * The key is the documentation path and the value contains
 * labels for each locale.
 *
 * @example
 * {
 *   "reference/core": {
 *     en: "Core",
 *     ar: "النواة"
 *   },
 *
 *   "reference/core/ui": {
 *     en: "UI",
 *     ar: "واجهة المستخدم"
 *   },
 *
 *   "reference/core/ui/utilities": {
 *     en: "Utilities",
 *     ar: "الأدوات المساعدة"
 *   }
 * }
 */
export interface SidebarTranslationMap {
  [path: string]: SidebarTranslations;
}

/**
 * Creates sidebar items from a nested documentation structure.
 *
 * The structure describes the directory hierarchy, while the
 * translation map provides localized labels for each path.
 *
 * Leaf nodes are automatically converted to Starlight
 * `autogenerate` entries.
 *
 * @param structure - Nested documentation directory structure.
 * @param translations - Flattened path-to-translations map.
 * @param options - Sidebar generation options.
 * @returns An array of Starlight-compatible sidebar groups.
 *
 * @example
 * const structure = {
 *   core: {
 *     math: {},
 *     ui: {
 *       utilities: {}
 *     }
 *   }
 * };
 *
 * const translations = {
 *   "reference/core": {
 *     en: "Core",
 *     ar: "النواة"
 *   },
 *   "reference/core/math": {
 *     en: "Math",
 *     ar: "الرياضيات"
 *   },
 *   "reference/core/ui": {
 *     en: "UI",
 *     ar: "واجهة المستخدم"
 *   },
 *   "reference/core/ui/utilities": {
 *     en: "Utilities",
 *     ar: "الأدوات المساعدة"
 *   }
 * };
 *
 * const items = createSidebarItems(
 *   structure,
 *   translations
 * );
 */
export function createSidebarItems(
  structure: SidebarStructure,
  translations?: SidebarTranslationMap,
  options?: CreateSidebarOptions,
): SidebarGroup[];

/**
 * Creates a complete Starlight sidebar group.
 *
 * The root group is generated from `rootDirectory`, while
 * its children are generated from the provided structure.
 *
 * @param structure - Nested documentation directory structure.
 * @param translations - Flattened path-to-translations map.
 * @param options - Sidebar generation options.
 * @returns A Starlight-compatible sidebar group.
 *
 * @example
 * const structure = {
 *   core: {
 *     math: {},
 *     ui: {
 *       utilities: {}
 *     }
 *   },
 *   wrapper: {},
 *   server: {}
 * };
 *
 * const translations = {
 *   reference: {
 *     en: "Reference",
 *     ar: "المرجع"
 *   },
 *
 *   "reference/core": {
 *     en: "Core",
 *     ar: "النواة"
 *   },
 *
 *   "reference/core/math": {
 *     en: "Math",
 *     ar: "الرياضيات"
 *   },
 *
 *   "reference/core/ui": {
 *     en: "UI",
 *     ar: "واجهة المستخدم"
 *   },
 *
 *   "reference/core/ui/utilities": {
 *     en: "Utilities",
 *     ar: "الأدوات المساعدة"
 *   },
 *
 *   "reference/wrapper": {
 *     en: "Wrapper",
 *     ar: "المغلّف"
 *   },
 *
 *   "reference/server": {
 *     en: "Server",
 *     ar: "الخادم"
 *   }
 * };
 *
 * const reference = createSidebar(
 *   structure,
 *   translations
 * );
 *
 * // Use directly in Starlight:
 * //
 * // starlight({
 * //   sidebar: [reference]
 * // });
 */
export function createSidebar(
  structure: SidebarStructure,
  translations?: SidebarTranslationMap,
  options?: CreateSidebarOptions,
): SidebarGroup;