/**
 * A map of locale identifiers to translated sidebar labels.
 *
 * @example
 * {
 *   en: "Core",
 *   ar: "النواة",
 *   fr: "Noyau"
 * }
 */
export interface SidebarLabels {
  [locale: string]: string;
}

/**
 * A flattened map of documentation paths to their
 * localized sidebar labels.
 *
 * The path also defines the sidebar hierarchy.
 *
 * @example
 * {
 *   "reference": {
 *     en: "Reference",
 *     ar: "المرجع"
 *   },
 *
 *   "reference/core": {
 *     en: "Core",
 *     ar: "النواة"
 *   },
 *
 *   "reference/core/ui": {
 *     en: "UI",
 *     ar: "واجهة المستخدم"
 *   },
 *
 *   "reference/core/ui/utilities": {
 *     en: "Utilities",
 *     ar: "الأدوات المساعدة"
 *   }
 * }
 */
export interface SidebarTranslations {
  [path: string]: SidebarLabels;
}

/**
 * Options for creating a Starlight sidebar.
 */
export interface CreateSidebarOptions {
  /**
   * Locale used for the primary `label`.
   *
   * Other locales are placed in Starlight's
   * `translations` property.
   *
   * @default "en"
   */
  locale?: string;

  /**
   * Root documentation directory.
   *
   * If omitted, the first path segment is used
   * as the root.
   *
   * @example
   * "reference"
   */
  rootDirectory?: string;
}

/**
 * A Starlight autogenerated sidebar item.
 */
export interface SidebarAutogenerateItem {
  autogenerate: {
    directory: string;
  };
}

/**
 * A generated Starlight sidebar item.
 */
export interface SidebarItem {
  /**
   * Label displayed for the selected locale.
   */
  label: string;

  /**
   * Labels for the remaining locales.
   */
  translations?: SidebarLabels;

  /**
   * Nested sidebar items.
   */
  items: Array<
    SidebarItem | SidebarAutogenerateItem
  >;
}

/**
 * Creates a complete translated Starlight sidebar
 * from a flattened path-based translation map.
 *
 * The directory hierarchy is inferred directly from
 * the translation keys.
 *
 * @param translations
 * A flattened map where each key represents a
 * documentation directory.
 *
 * @param options
 * Sidebar generation options.
 *
 * @returns A Starlight-compatible sidebar item.
 *
 * @example
 * import { createSidebar } from "starlight-sidebar";
 *
 * const ReferenceTranslations = {
 *   reference: {
 *     en: "Reference",
 *     ar: "المرجع"
 *   },
 *
 *   "reference/core": {
 *     en: "Core",
 *     ar: "النواة"
 *   },
 *
 *   "reference/core/ui": {
 *     en: "UI",
 *     ar: "واجهة المستخدم"
 *   },
 *
 *   "reference/core/ui/utilities": {
 *     en: "Utilities",
 *     ar: "الأدوات المساعدة"
 *   }
 * };
 *
 * const Reference = createSidebar(
 *   ReferenceTranslations
 * );
 *
 * // starlight({
 * //   sidebar: [Reference]
 * // });
 */
export function createSidebar(
  translations: SidebarTranslations,
  options?: CreateSidebarOptions,
): SidebarItem;

/**
 * Creates the nested items of a Starlight sidebar
 * without creating the root item.
 *
 * The hierarchy is inferred from the translation paths.
 *
 * @param translations
 * A flattened path-based translation map.
 *
 * @param options
 * Sidebar generation options.
 *
 * @returns An array of Starlight sidebar items.
 *
 * @example
 * import { createSidebarItems } from "starlight-sidebar";
 *
 * const items = createSidebarItems(
 *   ReferenceTranslations
 * );
 *
 * // starlight({
 * //   sidebar: [
 * //     {
 * //       label: "Reference",
 * //       items
 * //     }
 * //   ]
 * // });
 */
export function createSidebarItems(
  translations: SidebarTranslations,
  options?: CreateSidebarOptions,
): SidebarItem[];