/**
 * A collection of localized labels.
 *
 * @example
 * {
 *   en: "Core",
 *   ar: "النواة",
 *   fr: "Noyau"
 * }
 */
export interface SidebarTranslations {
  [locale: string]: string;
}

/**
 * A node in a nested sidebar structure.
 *
 * A node represents a documentation directory and can optionally
 * contain nested child nodes.
 *
 * @example
 * {
 *   translations: {
 *     en: "Core",
 *     ar: "النواة"
 *   },
 *   items: {
 *     ui: {
 *       translations: {
 *         en: "UI",
 *         ar: "واجهة المستخدم"
 *       }
 *     }
 *   }
 * }
 */
export interface SidebarNode {
  /**
   * Localized labels for the node.
   */
  translations?: SidebarTranslations;

  /**
   * Nested sidebar nodes.
   */
  items?: SidebarStructure;
}

/**
 * A nested documentation structure.
 *
 * Object keys represent directory names.
 *
 * @example
 * const structure = {
 *   core: {
 *     translations: {
 *       en: "Core",
 *       ar: "النواة"
 *     }
 *   },
 *   wrapper: {
 *     translations: {
 *       en: "Wrapper",
 *       ar: "المغلّف"
 *     }
 *   }
 * };
 */
export interface SidebarStructure {
  [directory: string]: SidebarNode;
}

/**
 * Starlight-compatible autogenerated directory item.
 */
export interface SidebarAutogenerate {
  autogenerate: {
    directory: string;
  };
}

/**
 * A Starlight-compatible sidebar item generated by this package.
 *
 * @example
 * {
 *   label: "Core",
 *   translations: {
 *     ar: "النواة"
 *   },
 *   items: [
 *     {
 *       autogenerate: {
 *         directory: "reference/core"
 *       }
 *     }
 *   ]
 * }
 */
export interface SidebarItem {
  /**
   * Label displayed for the default locale.
   */
  label: string;

  /**
   * Labels for additional locales.
   */
  translations?: SidebarTranslations;

  /**
   * Nested sidebar items.
   */
  items: Array<SidebarItem | SidebarAutogenerate>;
}

/**
 * Options for `createSidebarItems`.
 */
export interface CreateSidebarItemsOptions {
  /**
   * Locale used for the primary `label`.
   *
   * @default "en"
   *
   * @example
   * locale: "ar"
   */
  locale?: string;

  /**
   * Root directory used when generating documentation paths.
   *
   * @default "reference"
   *
   * @example
   * rootDirectory: "docs/api"
   */
  rootDirectory?: string;
}

/**
 * Options for `createSidebar`.
 *
 * @example
 * const options = {
 *   label: "Reference",
 *   translations: {
 *     en: "Reference",
 *     ar: "المرجع"
 *   },
 *   items: {
 *     core: {
 *       translations: {
 *         en: "Core",
 *         ar: "النواة"
 *       }
 *     }
 *   }
 * };
 */
export interface CreateSidebarOptions {
  /**
   * Fallback label for the sidebar section.
   */
  label: string;

  /**
   * Localized labels for the sidebar section.
   *
   * @example
   * {
   *   en: "Reference",
   *   ar: "المرجع"
   * }
   */
  translations?: SidebarTranslations;

  /**
   * Nested documentation structure.
   */
  items: SidebarStructure;

  /**
   * Locale used for the primary `label`.
   *
   * @default "en"
   */
  locale?: string;

  /**
   * Root directory used for generated documentation paths.
   *
   * @default "reference"
   */
  rootDirectory?: string;
}

/**
 * Recursively transforms a nested documentation structure into
 * Starlight-compatible sidebar items.
 *
 * Each object key represents a documentation directory.
 * Nodes containing `items` become nested sidebar groups, while
 * leaf nodes automatically generate their documentation directory.
 *
 * @param structure - Nested documentation structure.
 * @param options - Sidebar generation options.
 * @returns An array of generated sidebar items.
 *
 * @example
 * const items = createSidebarItems({
 *   core: {
 *     translations: {
 *       en: "Core",
 *       ar: "النواة"
 *     },
 *     items: {
 *       ui: {
 *         translations: {
 *           en: "UI",
 *           ar: "واجهة المستخدم"
 *         }
 *       }
 *     }
 *   }
 * });
 */
export function createSidebarItems(
  structure: SidebarStructure,
  options?: CreateSidebarItemsOptions,
): SidebarItem[];

/**
 * Creates a complete Starlight sidebar section from
 * a nested and multilingual documentation structure.
 *
 * @param options - Sidebar configuration.
 * @returns A Starlight-compatible sidebar section.
 *
 * @example
 * const reference = createSidebar({
 *   label: "Reference",
 *
 *   translations: {
 *     en: "Reference",
 *     ar: "المرجع"
 *   },
 *
 *   items: {
 *     core: {
 *       translations: {
 *         en: "Core",
 *         ar: "النواة"
 *       },
 *
 *       items: {
 *         ui: {
 *           translations: {
 *             en: "UI",
 *             ar: "واجهة المستخدم"
 *           }
 *         }
 *       }
 *     }
 *   }
 * });
 *
 * // Use with Starlight:
 * //
 * // sidebar: [
 * //   reference
 * // ]
 */
export function createSidebar(
  options: CreateSidebarOptions,
): SidebarItem;